Add default name to IngressClass and tidy SCC handling
nginxinc/nginx-ingress-operator pull request #130
Opened 2021-07-05 15:27 UTC by soneillf5

### Proposed changes
Fixes deletion bug, using the default name for the ingress class for deletion and creation.

Minor refactor to SCC resource handling.

### Checklist
Before creating a PR, run through this checklist and mark each as complete.

- [x] I have read the [CONTRIBUTING](https://github.com/nginxinc/nginx-ingress-operator/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that all unit tests pass after adding my changes
- [x] I have updated necessary documentation
- [x] I have rebased my branch onto master
- [x] I will ensure my PR is targeting the master branch and pulling from my branch from my own fork

2021-07-06 14:08 UTC, ciarams87 approved these changes

2021-07-06 16:05 UTC, ciarams87 requested changes
Actually after testing it out, this approach may not work - deleting the default ingressClass (a global resource) on a single ingress controller deletion will lead to difficulty when we have several ICs sharing the same resource.

2021-07-06 18:32 UTC, lucacome commented
I'm a little bit confused. What's the deletion bug?

2021-07-07 09:18 UTC, soneillf5 commented
@lucacome Sorry for the lack of description, the deletion bug is the following sequence:
- An IngressController is created
- 'controllers/prerequisites.go:18' checkPrerequisites is called before it's created
- this function creates an IngressClass if it doesn't exist. (L61)
- If the name of the IngressClass is not specified, it uses the default name 'nginx'
- A finaliser is added to CR resources, in this case an IngressController
- The IC is deleted
- In the reconcile loop, we see a finaliser needs to be addressed so 'finalizeNginxIngressController' is called
- This tries to delete the IngressClass but it fails as it can't find it an IngressClass with no name. 

Essentially, the deletion code isn't add the default value for the IngressClass name that the addition code did.

2021-07-07 09:29 UTC, vepatel approved these changes

2021-07-07 09:29 UTC, ciarams87 approved these changes

2021-07-07 11:51 UTC, merged